{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Part 1.  Pre-processing in Pandas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Note that this code must not run directly the Workbench in the graphical console. \n",
    "# Use python3, ipython3 or Jupyter notebook in a session's terminal, \n",
    "# See https://github.com/dask/dask/issues/4612\n",
    "\n",
    "import cdsw_dask_utils\n",
    "import cdsw\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Month</th>\n",
       "      <th>DayofMonth</th>\n",
       "      <th>DayOfWeek</th>\n",
       "      <th>CRSDepTime</th>\n",
       "      <th>CRSArrTime</th>\n",
       "      <th>UniqueCarrier</th>\n",
       "      <th>FlightNum</th>\n",
       "      <th>Origin</th>\n",
       "      <th>Dest</th>\n",
       "      <th>Cancelled</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>9</td>\n",
       "      <td>6</td>\n",
       "      <td>1331</td>\n",
       "      <td>1435</td>\n",
       "      <td>PI</td>\n",
       "      <td>942</td>\n",
       "      <td>SYR</td>\n",
       "      <td>BWI</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>10</td>\n",
       "      <td>7</td>\n",
       "      <td>1331</td>\n",
       "      <td>1435</td>\n",
       "      <td>PI</td>\n",
       "      <td>942</td>\n",
       "      <td>SYR</td>\n",
       "      <td>BWI</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>11</td>\n",
       "      <td>1</td>\n",
       "      <td>1331</td>\n",
       "      <td>1435</td>\n",
       "      <td>PI</td>\n",
       "      <td>942</td>\n",
       "      <td>SYR</td>\n",
       "      <td>BWI</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>3</td>\n",
       "      <td>1</td>\n",
       "      <td>12</td>\n",
       "      <td>2</td>\n",
       "      <td>1331</td>\n",
       "      <td>1435</td>\n",
       "      <td>PI</td>\n",
       "      <td>942</td>\n",
       "      <td>SYR</td>\n",
       "      <td>BWI</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>13</td>\n",
       "      <td>3</td>\n",
       "      <td>1331</td>\n",
       "      <td>1435</td>\n",
       "      <td>PI</td>\n",
       "      <td>942</td>\n",
       "      <td>SYR</td>\n",
       "      <td>BWI</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   Month  DayofMonth  DayOfWeek  CRSDepTime  CRSArrTime UniqueCarrier  \\\n",
       "0      1           9          6        1331        1435            PI   \n",
       "1      1          10          7        1331        1435            PI   \n",
       "2      1          11          1        1331        1435            PI   \n",
       "3      1          12          2        1331        1435            PI   \n",
       "4      1          13          3        1331        1435            PI   \n",
       "\n",
       "   FlightNum Origin Dest  Cancelled  \n",
       "0        942    SYR  BWI          0  \n",
       "1        942    SYR  BWI          0  \n",
       "2        942    SYR  BWI          0  \n",
       "3        942    SYR  BWI          0  \n",
       "4        942    SYR  BWI          0  "
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# read flights dataset\n",
    "input_file = \"data/1988.csv.bz2\"\n",
    "columns = ['Month','DayofMonth','DayOfWeek','CRSDepTime','CRSArrTime','UniqueCarrier','FlightNum',\n",
    "           'Origin','Dest','Cancelled']\n",
    "flight_df = pd.read_csv(input_file,sep=',',header=0, na_values='NA', usecols=columns )\n",
    "flight_df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 5202096 entries, 0 to 5202095\n",
      "Data columns (total 10 columns):\n",
      "Month            int64\n",
      "DayofMonth       int64\n",
      "DayOfWeek        int64\n",
      "CRSDepTime       int64\n",
      "CRSArrTime       int64\n",
      "UniqueCarrier    object\n",
      "FlightNum        int64\n",
      "Origin           object\n",
      "Dest             object\n",
      "Cancelled        int64\n",
      "dtypes: int64(7), object(3)\n",
      "memory usage: 396.9+ MB\n"
     ]
    }
   ],
   "source": [
    "flight_df.info()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Feature Engineering\n",
    "#### 1. create routes from origin and destination"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "LAX_SFO    20750\n",
       "SFO_LAX    20658\n",
       "LAX_PHX    13461\n",
       "PHX_LAX    13273\n",
       "LAX_LAS    12175\n",
       "LGA_BOS    12027\n",
       "LAS_LAX    11801\n",
       "SJC_LAX    11535\n",
       "LAX_SJC    11292\n",
       "BOS_LGA    11141\n",
       "Name: route, dtype: int64"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import numpy as np\n",
    "# feature engineering - Create routes\n",
    "flight_df['route'] = flight_df['Origin'] + \"_\" + flight_df['Dest']\n",
    "\n",
    "# show top 20 routes - As defined by nb of flights\n",
    "top_routes = flight_df['route'].value_counts(ascending=False)\n",
    "top_routes.head(10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>route</th>\n",
       "      <th>count</th>\n",
       "      <th>nb_cancelled</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <td>1920</td>\n",
       "      <td>LAX_SFO</td>\n",
       "      <td>20750</td>\n",
       "      <td>228</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>3375</td>\n",
       "      <td>SFO_LAX</td>\n",
       "      <td>20658</td>\n",
       "      <td>206</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>1911</td>\n",
       "      <td>LAX_PHX</td>\n",
       "      <td>13461</td>\n",
       "      <td>78</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>2870</td>\n",
       "      <td>PHX_LAX</td>\n",
       "      <td>13273</td>\n",
       "      <td>71</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>1894</td>\n",
       "      <td>LAX_LAS</td>\n",
       "      <td>12175</td>\n",
       "      <td>58</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>1956</td>\n",
       "      <td>LGA_BOS</td>\n",
       "      <td>12027</td>\n",
       "      <td>287</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>1840</td>\n",
       "      <td>LAS_LAX</td>\n",
       "      <td>11801</td>\n",
       "      <td>47</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>3432</td>\n",
       "      <td>SJC_LAX</td>\n",
       "      <td>11535</td>\n",
       "      <td>71</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>1921</td>\n",
       "      <td>LAX_SJC</td>\n",
       "      <td>11292</td>\n",
       "      <td>71</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>366</td>\n",
       "      <td>BOS_LGA</td>\n",
       "      <td>11141</td>\n",
       "      <td>243</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "        route  count  nb_cancelled\n",
       "1920  LAX_SFO  20750           228\n",
       "3375  SFO_LAX  20658           206\n",
       "1911  LAX_PHX  13461            78\n",
       "2870  PHX_LAX  13273            71\n",
       "1894  LAX_LAS  12175            58\n",
       "1956  LGA_BOS  12027           287\n",
       "1840  LAS_LAX  11801            47\n",
       "3432  SJC_LAX  11535            71\n",
       "1921  LAX_SJC  11292            71\n",
       "366   BOS_LGA  11141           243"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#look at their cancelations\n",
    "flight_df[['route', 'Cancelled']].groupby('route')\\\n",
    "        .agg({'route':'size', 'Cancelled':'sum'}) \\\n",
    "        .rename(columns={'route':'count','Cancelled':'nb_cancelled'}) \\\n",
    "        .reset_index()\\\n",
    "        .sort_values(['count'],ascending=False)\\\n",
    "        .head(10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "Int64Index: 487253 entries, 786 to 5201496\n",
      "Data columns (total 11 columns):\n",
      "Month            487253 non-null int64\n",
      "DayofMonth       487253 non-null int64\n",
      "DayOfWeek        487253 non-null int64\n",
      "CRSDepTime       487253 non-null int64\n",
      "CRSArrTime       487253 non-null int64\n",
      "UniqueCarrier    487253 non-null object\n",
      "FlightNum        487253 non-null int64\n",
      "Origin           487253 non-null object\n",
      "Dest             487253 non-null object\n",
      "Cancelled        487253 non-null int64\n",
      "route            487253 non-null object\n",
      "dtypes: int64(7), object(4)\n",
      "memory usage: 44.6+ MB\n"
     ]
    }
   ],
   "source": [
    "#focus on 50 biggest routes - As defined by nb of flights \n",
    "route_lst=top_routes.head(50)\n",
    "flight_df = flight_df[flight_df['route'].isin(route_lst.index)]\n",
    "flight_df.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Month            0\n",
       "DayofMonth       0\n",
       "DayOfWeek        0\n",
       "CRSDepTime       0\n",
       "CRSArrTime       0\n",
       "UniqueCarrier    0\n",
       "FlightNum        0\n",
       "Origin           0\n",
       "Dest             0\n",
       "Cancelled        0\n",
       "route            0\n",
       "dtype: int64"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Quick sanity check - count number of null values()\n",
    "flight_df.isnull().sum()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### 2. Feature and label encoding encoding\n",
    "Label encoding"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ### encode labels \n",
    "flight_df.Cancelled = pd.Categorical(flight_df.Cancelled)\n",
    "flight_df['Label'] = flight_df.Cancelled.cat.codes\n",
    "flight_df.drop(['Cancelled'], axis=1, inplace=True)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Feature encoding "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array(['ATL', 'BOS', 'DAL', 'DCA', 'DEN', 'DFW', 'DTW', 'EWR', 'HOU',\n",
       "       'IAH', 'LAS', 'LAX', 'LGA', 'MCO', 'MIA', 'MSP', 'ORD', 'PDX',\n",
       "       'PHX', 'SAN', 'SAT', 'SEA', 'SFO', 'SJC', 'STL'], dtype=object)"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Get airport unique values\n",
    "import numpy as np\n",
    "airport_list = np.unique(np.concatenate((np.sort(flight_df['Origin'].unique()),\n",
    "                                         np.sort(flight_df['Dest'].unique())))\n",
    "                        )\n",
    "airport_list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Encode categorical features - Sklearn only supports numerical values\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "\n",
    "# encode airlines \n",
    "le_carrier = LabelEncoder()\n",
    "flight_df['Carrier_encoded'] = le_carrier.fit_transform(flight_df['UniqueCarrier'])\n",
    "\n",
    "# Encode airports : Using same encoder for both origin and dest ( consistent encoding of airports )\n",
    "le_airport = LabelEncoder()\n",
    "le_airport.fit(airport_list)\n",
    "flight_df['Origin_encoded'] = le_airport.transform(flight_df['Origin'])\n",
    "flight_df['Dest_encoded'] = le_airport.transform(flight_df['Dest'])\n",
    "\n",
    "# Encode routes \n",
    "le_route = LabelEncoder()\n",
    "flight_df['route_encoded'] = le_route.fit_transform(flight_df['route'])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>UniqueCarrier</th>\n",
       "      <th>Carrier_encoded</th>\n",
       "      <th>Origin</th>\n",
       "      <th>Origin_encoded</th>\n",
       "      <th>Dest</th>\n",
       "      <th>Dest_encoded</th>\n",
       "      <th>route</th>\n",
       "      <th>route_encoded</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <td>1737619</td>\n",
       "      <td>TW</td>\n",
       "      <td>10</td>\n",
       "      <td>ORD</td>\n",
       "      <td>16</td>\n",
       "      <td>STL</td>\n",
       "      <td>24</td>\n",
       "      <td>ORD_STL</td>\n",
       "      <td>33</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>4312164</td>\n",
       "      <td>CO</td>\n",
       "      <td>2</td>\n",
       "      <td>EWR</td>\n",
       "      <td>7</td>\n",
       "      <td>BOS</td>\n",
       "      <td>1</td>\n",
       "      <td>EWR_BOS</td>\n",
       "      <td>10</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>2001821</td>\n",
       "      <td>DL</td>\n",
       "      <td>3</td>\n",
       "      <td>LAX</td>\n",
       "      <td>11</td>\n",
       "      <td>SAN</td>\n",
       "      <td>19</td>\n",
       "      <td>LAX_SAN</td>\n",
       "      <td>18</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>3975288</td>\n",
       "      <td>US</td>\n",
       "      <td>12</td>\n",
       "      <td>SFO</td>\n",
       "      <td>22</td>\n",
       "      <td>LAX</td>\n",
       "      <td>11</td>\n",
       "      <td>SFO_LAX</td>\n",
       "      <td>45</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>2780453</td>\n",
       "      <td>PA (1)</td>\n",
       "      <td>7</td>\n",
       "      <td>LAX</td>\n",
       "      <td>11</td>\n",
       "      <td>SAN</td>\n",
       "      <td>19</td>\n",
       "      <td>LAX_SAN</td>\n",
       "      <td>18</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>1204005</td>\n",
       "      <td>AA</td>\n",
       "      <td>0</td>\n",
       "      <td>STL</td>\n",
       "      <td>24</td>\n",
       "      <td>ORD</td>\n",
       "      <td>16</td>\n",
       "      <td>STL_ORD</td>\n",
       "      <td>49</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>2515899</td>\n",
       "      <td>AA</td>\n",
       "      <td>0</td>\n",
       "      <td>ORD</td>\n",
       "      <td>16</td>\n",
       "      <td>ATL</td>\n",
       "      <td>0</td>\n",
       "      <td>ORD_ATL</td>\n",
       "      <td>27</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>1562629</td>\n",
       "      <td>DL</td>\n",
       "      <td>3</td>\n",
       "      <td>ORD</td>\n",
       "      <td>16</td>\n",
       "      <td>ATL</td>\n",
       "      <td>0</td>\n",
       "      <td>ORD_ATL</td>\n",
       "      <td>27</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>2553223</td>\n",
       "      <td>US</td>\n",
       "      <td>12</td>\n",
       "      <td>DCA</td>\n",
       "      <td>3</td>\n",
       "      <td>BOS</td>\n",
       "      <td>1</td>\n",
       "      <td>DCA_BOS</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>2147141</td>\n",
       "      <td>US</td>\n",
       "      <td>12</td>\n",
       "      <td>SAN</td>\n",
       "      <td>19</td>\n",
       "      <td>LAX</td>\n",
       "      <td>11</td>\n",
       "      <td>SAN_LAX</td>\n",
       "      <td>38</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "        UniqueCarrier  Carrier_encoded Origin  Origin_encoded Dest  \\\n",
       "1737619            TW               10    ORD              16  STL   \n",
       "4312164            CO                2    EWR               7  BOS   \n",
       "2001821            DL                3    LAX              11  SAN   \n",
       "3975288            US               12    SFO              22  LAX   \n",
       "2780453        PA (1)                7    LAX              11  SAN   \n",
       "1204005            AA                0    STL              24  ORD   \n",
       "2515899            AA                0    ORD              16  ATL   \n",
       "1562629            DL                3    ORD              16  ATL   \n",
       "2553223            US               12    DCA               3  BOS   \n",
       "2147141            US               12    SAN              19  LAX   \n",
       "\n",
       "         Dest_encoded    route  route_encoded  \n",
       "1737619            24  ORD_STL             33  \n",
       "4312164             1  EWR_BOS             10  \n",
       "2001821            19  LAX_SAN             18  \n",
       "3975288            11  SFO_LAX             45  \n",
       "2780453            19  LAX_SAN             18  \n",
       "1204005            16  STL_ORD             49  \n",
       "2515899             0  ORD_ATL             27  \n",
       "1562629             0  ORD_ATL             27  \n",
       "2553223             1  DCA_BOS              5  \n",
       "2147141            11  SAN_LAX             38  "
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Viewing few rows of make and its encoded columns\n",
    "flight_df[['UniqueCarrier','Carrier_encoded','Origin','Origin_encoded',\n",
    "           'Dest', 'Dest_encoded', 'route', 'route_encoded' ]].sample(10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "# # 2. Build a classification model using MLLib\n",
    "# ### Split Test/Train\n",
    "\n",
    "from sklearn.model_selection import train_test_split\n",
    "X_train, X_test, y_train, y_test = train_test_split(flight_df.drop(['UniqueCarrier','Origin','Dest','route'],axis=1),\n",
    "                                                    flight_df['Label'], \n",
    "                                                    test_size=0.3, \n",
    "                                                    random_state=100)\n",
    "del flight_df # free up some memory"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "Int64Index: 341077 entries, 936357 to 3164854\n",
      "Data columns (total 11 columns):\n",
      "Month              341077 non-null int64\n",
      "DayofMonth         341077 non-null int64\n",
      "DayOfWeek          341077 non-null int64\n",
      "CRSDepTime         341077 non-null int64\n",
      "CRSArrTime         341077 non-null int64\n",
      "FlightNum          341077 non-null int64\n",
      "Label              341077 non-null int8\n",
      "Carrier_encoded    341077 non-null int64\n",
      "Origin_encoded     341077 non-null int64\n",
      "Dest_encoded       341077 non-null int64\n",
      "route_encoded      341077 non-null int64\n",
      "dtypes: int64(10), int8(1)\n",
      "memory usage: 28.9 MB\n"
     ]
    }
   ],
   "source": [
    "X_train.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "Int64Index: 146176 entries, 1856532 to 3419091\n",
      "Data columns (total 11 columns):\n",
      "Month              146176 non-null int64\n",
      "DayofMonth         146176 non-null int64\n",
      "DayOfWeek          146176 non-null int64\n",
      "CRSDepTime         146176 non-null int64\n",
      "CRSArrTime         146176 non-null int64\n",
      "FlightNum          146176 non-null int64\n",
      "Label              146176 non-null int8\n",
      "Carrier_encoded    146176 non-null int64\n",
      "Origin_encoded     146176 non-null int64\n",
      "Dest_encoded       146176 non-null int64\n",
      "route_encoded      146176 non-null int64\n",
      "dtypes: int64(10), int8(1)\n",
      "memory usage: 12.4 MB\n"
     ]
    }
   ],
   "source": [
    "X_test.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Part 2 : Model Training - Using SKLEARN "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[2, 4, 6, 8, 10]\n",
      "[2, 4, 6, 8, 10]\n"
     ]
    }
   ],
   "source": [
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.model_selection import GridSearchCV\n",
    "\n",
    "# ### parameters for grid search\n",
    "param_numTrees = list(range(2,12,2))\n",
    "print(param_numTrees)\n",
    "param_maxDepth = list(range(2,12,2))\n",
    "print(param_maxDepth)\n",
    "\n",
    "rfc = RandomForestClassifier(random_state=10, n_jobs=-1)\n",
    "\n",
    "GS_params = { \n",
    "    'n_estimators': param_numTrees,\n",
    "    'max_depth' : param_maxDepth\n",
    "}\n",
    "\n",
    "CV_rfc = GridSearchCV(estimator=rfc, \n",
    "                      param_grid=GS_params, \n",
    "                      cv= 3,\n",
    "                      verbose = 1,\n",
    "                      n_jobs=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fitting 3 folds for each of 25 candidates, totalling 75 fits\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.\n",
      "[Parallel(n_jobs=1)]: Done  75 out of  75 | elapsed:  2.5min finished\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "GridSearchCV(cv=3, error_score='raise-deprecating',\n",
       "             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,\n",
       "                                              criterion='gini', max_depth=None,\n",
       "                                              max_features='auto',\n",
       "                                              max_leaf_nodes=None,\n",
       "                                              min_impurity_decrease=0.0,\n",
       "                                              min_impurity_split=None,\n",
       "                                              min_samples_leaf=1,\n",
       "                                              min_samples_split=2,\n",
       "                                              min_weight_fraction_leaf=0.0,\n",
       "                                              n_estimators='warn', n_jobs=-1,\n",
       "                                              oob_score=False, random_state=10,\n",
       "                                              verbose=0, warm_start=False),\n",
       "             iid='warn', n_jobs=1,\n",
       "             param_grid={'max_depth': [2, 4, 6, 8, 10],\n",
       "                         'n_estimators': [2, 4, 6, 8, 10]},\n",
       "             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,\n",
       "             scoring=None, verbose=1)"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "## Train model\n",
    "CV_rfc.fit(X_train, y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'max_depth': 2, 'n_estimators': 2}\n"
     ]
    }
   ],
   "source": [
    "# ### Show Best Parameters \n",
    "print(CV_rfc.best_params_)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Evaluate model performance"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "              precision    recall  f1-score   support\n",
      "\n",
      "           0       1.00      1.00      1.00    144393\n",
      "           1       1.00      1.00      1.00      1783\n",
      "\n",
      "    accuracy                           1.00    146176\n",
      "   macro avg       1.00      1.00      1.00    146176\n",
      "weighted avg       1.00      1.00      1.00    146176\n",
      "\n"
     ]
    }
   ],
   "source": [
    "from sklearn.metrics import classification_report\n",
    "# ## fit test dataset \n",
    "y_true, y_pred = y_test, CV_rfc.predict(X_test)\n",
    "# ## Print classification metrics \n",
    "print(classification_report(y_true, y_pred))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Part 3. Distributed training using DASK Backend"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Waiting for Dask scheduler to become ready...\n",
      "Dask scheduler is ready\n",
      "IDs ['kn9lios60mp1lb5g', '9qgxbev6j8g719o6', 'gnhy7vaq19rdpkbx']\n"
     ]
    }
   ],
   "source": [
    "# Run a Dask cluster with three workers and return an object containing\n",
    "# a description of the cluster. \n",
    "# \n",
    "# The Dask_utils helper library will\n",
    "# - launch the requested number of workers \n",
    "# - launch the Dask cluster ( Scheduler + workers )\n",
    "#\n",
    "# Note that the scheduler will run in the current session, and the Dask\n",
    "# dashboard will become available in the nine-dot menu at the upper\n",
    "# right corner of the CDSW app.\n",
    "\n",
    "cluster = cdsw_dask_utils.run_dask_cluster(\n",
    "  n=3, \\\n",
    "  cpu=1, \\\n",
    "  memory=3, \\\n",
    "  nvidia_gpu=0\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<a  target=\"_blank\" rel=\"noopener noreferrer\" href=\"http://read-only-bfq4vig8clppz7bq.ml-2f4cffbb-91e.demo-aws.ylcu-atmi.cloudera.site\">http://read-only-bfq4vig8clppz7bq.ml-2f4cffbb-91e.demo-aws.ylcu-atmi.cloudera.site</a>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Get the Dask Scheduler UI\n",
    "import os \n",
    "engine_id = os.environ.get('CDSW_ENGINE_ID')\n",
    "cdsw_domain = os.environ.get('CDSW_DOMAIN')\n",
    "\n",
    "from IPython.core.display import HTML\n",
    "HTML('<a  target=\"_blank\" rel=\"noopener noreferrer\" href=\"http://read-only-{}.{}\">http://read-only-{}.{}</a>'\n",
    "     .format(engine_id,cdsw_domain,engine_id,cdsw_domain))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [],
   "source": [
    "# #### Connect a Dask client to the scheduler address in the cluster\n",
    "\n",
    "from dask.distributed import Client\n",
    "client = Client(cluster[\"scheduler_address\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[2, 4, 6, 8, 10]\n",
      "[2, 4, 6, 8, 10]\n"
     ]
    }
   ],
   "source": [
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.model_selection import GridSearchCV\n",
    "\n",
    "# ### parameters for grid search\n",
    "param_numTrees = list(range(2,12,2))\n",
    "print(param_numTrees)\n",
    "param_maxDepth = list(range(2,12,2))\n",
    "print(param_maxDepth)\n",
    "\n",
    "rfc = RandomForestClassifier(random_state=10, n_jobs=-1)\n",
    "\n",
    "GS_params = { \n",
    "    'n_estimators': param_numTrees,\n",
    "    'max_depth' : param_maxDepth\n",
    "}\n",
    "\n",
    "CV_rfc = GridSearchCV(estimator=rfc, \n",
    "                      param_grid=GS_params, \n",
    "                      cv= 3,\n",
    "                      verbose = 1,\n",
    "                      n_jobs=-1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fitting 3 folds for each of 25 candidates, totalling 75 fits\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[Parallel(n_jobs=-1)]: Using backend DaskDistributedBackend with 80 concurrent workers.\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9037bf8> of <Future: status: cancelled, key: _fit_and_score-batch-f4180c3f206c4accbe30005084b5b3b3>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-f4180c3f206c4accbe30005084b5b3b3\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9037400> of <Future: status: cancelled, key: _fit_and_score-batch-ff454b8f84994d1db67cfe0c6f0a6af8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-ff454b8f84994d1db67cfe0c6f0a6af8\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc6554268> of <Future: status: cancelled, key: _fit_and_score-batch-1d00f0b0f8f34b949fff5bca3199fdce>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-1d00f0b0f8f34b949fff5bca3199fdce\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc907c840> of <Future: status: cancelled, key: _fit_and_score-batch-a648de9833874219b0bf8ad8a86af5d8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-a648de9833874219b0bf8ad8a86af5d8\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9008c80> of <Future: status: cancelled, key: _fit_and_score-batch-a28d2d22958b436da8e6f0b733784b99>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-a28d2d22958b436da8e6f0b733784b99\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9018bf8> of <Future: status: cancelled, key: _fit_and_score-batch-3c71418ac2e844a5b2b91b2057c9bc35>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-3c71418ac2e844a5b2b91b2057c9bc35\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9073268> of <Future: status: cancelled, key: _fit_and_score-batch-446d98904fdb474ca7dbc81ab6eaae8a>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-446d98904fdb474ca7dbc81ab6eaae8a\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc90087b8> of <Future: status: cancelled, key: _fit_and_score-batch-a385538cff51466f825f0118bac3769c>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-a385538cff51466f825f0118bac3769c\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc6554598> of <Future: status: cancelled, key: _fit_and_score-batch-0d15dd90b41a4d85b462549d0e30f48a>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-0d15dd90b41a4d85b462549d0e30f48a\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9037f28> of <Future: status: cancelled, key: _fit_and_score-batch-0f063c9ebaa8416596345b0068f93661>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-0f063c9ebaa8416596345b0068f93661\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc6554950> of <Future: status: cancelled, key: _fit_and_score-batch-35946859cb6549ee9f19d673f06a517f>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-35946859cb6549ee9f19d673f06a517f\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dddc6de18> of <Future: status: cancelled, key: _fit_and_score-batch-3a3bf37bc7584c2aa634173994d7e044>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-3a3bf37bc7584c2aa634173994d7e044\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc907c378> of <Future: status: cancelled, key: _fit_and_score-batch-561a1a977eaf4519b5eeeb7dbb8d7321>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-561a1a977eaf4519b5eeeb7dbb8d7321\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc90188c8> of <Future: status: cancelled, key: _fit_and_score-batch-d4c94bc419e545068f3aa2b6549731cb>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-d4c94bc419e545068f3aa2b6549731cb\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc6554c80> of <Future: status: cancelled, key: _fit_and_score-batch-352953d6e6de4221a409c500ee84b676>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-352953d6e6de4221a409c500ee84b676\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc907cea0> of <Future: status: cancelled, key: _fit_and_score-batch-e96836f27b854a17b5f67e7b75e0a17f>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-e96836f27b854a17b5f67e7b75e0a17f\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9008488> of <Future: status: cancelled, key: _fit_and_score-batch-053784ee43494df7a168e06cc8bfabdc>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-053784ee43494df7a168e06cc8bfabdc\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc902c7b8> of <Future: status: cancelled, key: _fit_and_score-batch-9aad0d9b39b3411fbfacd06f64db1332>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-9aad0d9b39b3411fbfacd06f64db1332\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc90378c8> of <Future: status: cancelled, key: _fit_and_score-batch-61e6dfd1ea574a8f8a863f28c26834af>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-61e6dfd1ea574a8f8a863f28c26834af\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc6548510> of <Future: status: cancelled, key: _fit_and_score-batch-40f65a4fee4d4744ad50f9a468efd3e2>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-40f65a4fee4d4744ad50f9a468efd3e2\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9018268> of <Future: status: cancelled, key: _fit_and_score-batch-03683e57833d47aeb56de729e0c3c0e0>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-03683e57833d47aeb56de729e0c3c0e0\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9073a60> of <Future: status: cancelled, key: _fit_and_score-batch-25ccbd8219f64e22a2c3a6b5af048487>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-25ccbd8219f64e22a2c3a6b5af048487\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc907c048> of <Future: status: cancelled, key: _fit_and_score-batch-251ffe8d84b14701a5b23b0ea4e7f880>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-251ffe8d84b14701a5b23b0ea4e7f880\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9018598> of <Future: status: cancelled, key: _fit_and_score-batch-970b3984c7514f54ad1161cf886a60dd>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-970b3984c7514f54ad1161cf886a60dd\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc6548048> of <Future: status: cancelled, key: _fit_and_score-batch-d3fbca100d5c4e17999432e39ea6163d>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-d3fbca100d5c4e17999432e39ea6163d\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9073730> of <Future: status: cancelled, key: _fit_and_score-batch-bc9f6d279bbf49c6b9b39a235c2706c2>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-bc9f6d279bbf49c6b9b39a235c2706c2\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc907cb70> of <Future: status: cancelled, key: _fit_and_score-batch-84982d104d9b4754b6eeeacb6ef69839>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-84982d104d9b4754b6eeeacb6ef69839\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9008158> of <Future: status: cancelled, key: _fit_and_score-batch-76d03ab83c4c43fbaba92a31a6574d24>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-76d03ab83c4c43fbaba92a31a6574d24\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc902c488> of <Future: status: cancelled, key: _fit_and_score-batch-d60610899c98475c9227739e859ebddc>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-d60610899c98475c9227739e859ebddc\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc6548840> of <Future: status: cancelled, key: _fit_and_score-batch-9fb09e426bb74cc2bf8b07e29caeb4a2>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-9fb09e426bb74cc2bf8b07e29caeb4a2\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc5092d90> of <Future: status: cancelled, key: _fit_and_score-batch-a4fe6fa605f6438c9d7edafc1f400949>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-a4fe6fa605f6438c9d7edafc1f400949\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5da4eff1e0> of <Future: status: cancelled, key: _fit_and_score-batch-a62b2dacc1dc4fbd8111e45cb70914b0>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-a62b2dacc1dc4fbd8111e45cb70914b0\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc90738c8> of <Future: status: cancelled, key: _fit_and_score-batch-22acc807f41e43a293e0b6a291a71203>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-22acc807f41e43a293e0b6a291a71203\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9073598> of <Future: status: cancelled, key: _fit_and_score-batch-d23168ef154f4a0bac20e913c9400467>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-d23168ef154f4a0bac20e913c9400467\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9073400> of <Future: status: cancelled, key: _fit_and_score-batch-0ffd2d0252e6440d84cd01463c52abb2>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-0ffd2d0252e6440d84cd01463c52abb2\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc90730d0> of <Future: status: cancelled, key: _fit_and_score-batch-b5e1dd93cfee476b8ae5f280f3c228c1>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-b5e1dd93cfee476b8ae5f280f3c228c1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc907cd08> of <Future: status: cancelled, key: _fit_and_score-batch-46e451c4c3ba40079bc923059abc1db1>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-46e451c4c3ba40079bc923059abc1db1\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc907c9d8> of <Future: status: cancelled, key: _fit_and_score-batch-9081f0a9674d469aab9c079813ececc7>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-9081f0a9674d469aab9c079813ececc7\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc907c6a8> of <Future: status: cancelled, key: _fit_and_score-batch-715b203098fb468a9cbacb9f478e5ab7>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-715b203098fb468a9cbacb9f478e5ab7\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc907c510> of <Future: status: cancelled, key: _fit_and_score-batch-af41b1fd617741858806c22f1cba2028>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-af41b1fd617741858806c22f1cba2028\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc907c1e0> of <Future: status: cancelled, key: _fit_and_score-batch-7721f190238a473693acd4259eb431ea>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-7721f190238a473693acd4259eb431ea\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9008e18> of <Future: status: cancelled, key: _fit_and_score-batch-77660863eff84b34932cee929b7d02b1>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-77660863eff84b34932cee929b7d02b1\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9008ae8> of <Future: status: cancelled, key: _fit_and_score-batch-c7a6300f792142b8bb8aa0a0a55b694f>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-c7a6300f792142b8bb8aa0a0a55b694f\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9008950> of <Future: status: cancelled, key: _fit_and_score-batch-8ceffff7bace4ec98d9e847cbb03af10>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-8ceffff7bace4ec98d9e847cbb03af10\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9008620> of <Future: status: cancelled, key: _fit_and_score-batch-9cdf38b641364f579fd73aa31185188d>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-9cdf38b641364f579fd73aa31185188d\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc90082f0> of <Future: status: cancelled, key: _fit_and_score-batch-84df7171f5ca43e9b4ef12aef98f6f83>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-84df7171f5ca43e9b4ef12aef98f6f83\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9018f28> of <Future: status: cancelled, key: _fit_and_score-batch-fff474fff2f74555b82f24f8306bfa93>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-fff474fff2f74555b82f24f8306bfa93\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9018d90> of <Future: status: cancelled, key: _fit_and_score-batch-93f3155490d046d3aa2581f3c00c6221>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-93f3155490d046d3aa2581f3c00c6221\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9018a60> of <Future: status: cancelled, key: _fit_and_score-batch-beb45c0f961e4c14a399858a72def8aa>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-beb45c0f961e4c14a399858a72def8aa\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9018730> of <Future: status: cancelled, key: _fit_and_score-batch-eb0c07a8c53c4a5e9fd82d91ed6b7c4e>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-eb0c07a8c53c4a5e9fd82d91ed6b7c4e\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9018400> of <Future: status: cancelled, key: _fit_and_score-batch-98adae79e8fb4acab6b6936b1f17eacd>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-98adae79e8fb4acab6b6936b1f17eacd\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc90180d0> of <Future: status: cancelled, key: _fit_and_score-batch-a246a604333947108fa0643f6892bdf6>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-a246a604333947108fa0643f6892bdf6\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9023ea0> of <Future: status: cancelled, key: _fit_and_score-batch-db182c299a2a494596c730cda7e9d5c6>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-db182c299a2a494596c730cda7e9d5c6\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc902c950> of <Future: status: cancelled, key: _fit_and_score-batch-57501502ab0e4608b098f03763f91ec0>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-57501502ab0e4608b098f03763f91ec0\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc902c620> of <Future: status: cancelled, key: _fit_and_score-batch-ae1b65f5596e48a69e8c03800dc2fe44>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-ae1b65f5596e48a69e8c03800dc2fe44\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc902c2f0> of <Future: status: cancelled, key: _fit_and_score-batch-87bccaa1b5084be9ada3e0d2427a4eb8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-87bccaa1b5084be9ada3e0d2427a4eb8\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc902c158> of <Future: status: cancelled, key: _fit_and_score-batch-85689d8b80274a5a956806662e49c76a>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-85689d8b80274a5a956806662e49c76a\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9037d90> of <Future: status: cancelled, key: _fit_and_score-batch-59a8e62a0d16446787ecd4251d813238>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-59a8e62a0d16446787ecd4251d813238\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9037a60> of <Future: status: cancelled, key: _fit_and_score-batch-01f6462172c14d29a6ace6b8023db670>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-01f6462172c14d29a6ace6b8023db670\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9037730> of <Future: status: cancelled, key: _fit_and_score-batch-6c97c3ff5bd54d3885dd2ad8aaba50c2>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-6c97c3ff5bd54d3885dd2ad8aaba50c2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9037598> of <Future: status: cancelled, key: _fit_and_score-batch-b5856830f9384f1494daaffeccc3afb9>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-b5856830f9384f1494daaffeccc3afb9\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc9037268> of <Future: status: cancelled, key: _fit_and_score-batch-1f5a2b56fa34425891a752fc69a151c5>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-1f5a2b56fa34425891a752fc69a151c5\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc65489d8> of <Future: status: cancelled, key: _fit_and_score-batch-789b9deac77a44c1aacae41eb3ac2ee1>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-789b9deac77a44c1aacae41eb3ac2ee1\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc65486a8> of <Future: status: cancelled, key: _fit_and_score-batch-f6839005c9a34ca895cd0c1c43899961>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-f6839005c9a34ca895cd0c1c43899961\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc6548378> of <Future: status: cancelled, key: _fit_and_score-batch-fa583b50406746e0be7b1c951f6a9619>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-fa583b50406746e0be7b1c951f6a9619\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc65481e0> of <Future: status: cancelled, key: _fit_and_score-batch-ded653709aaa413797a6854d22287f36>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-ded653709aaa413797a6854d22287f36\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc6554e18> of <Future: status: cancelled, key: _fit_and_score-batch-928e0427c73d45ff88d5fc5e90242cdd>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-928e0427c73d45ff88d5fc5e90242cdd\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc6554ae8> of <Future: status: cancelled, key: _fit_and_score-batch-f20af8505c6c4edfb50b7f203292fcc4>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-f20af8505c6c4edfb50b7f203292fcc4\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc65547b8> of <Future: status: cancelled, key: _fit_and_score-batch-18348b287f0a46ffbf8946c92ce3feed>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-18348b287f0a46ffbf8946c92ce3feed\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc65540d0> of <Future: status: cancelled, key: _fit_and_score-batch-6529f61240704411a773191f2b1f6301>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-6529f61240704411a773191f2b1f6301\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dc65542f0> of <Future: status: cancelled, key: _fit_and_score-batch-acfebc67afc3424baad30d262ced0c01>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-acfebc67afc3424baad30d262ced0c01\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dddc6d950> of <Future: status: cancelled, key: _fit_and_score-batch-976837c353c84c18b85ef31daef4872c>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-976837c353c84c18b85ef31daef4872c\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dddc6d8c8> of <Future: status: cancelled, key: _fit_and_score-batch-7ac4f0b222d847ccb56715d9ca61b487>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-7ac4f0b222d847ccb56715d9ca61b487\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5da4ef3ea0> of <Future: status: cancelled, key: _fit_and_score-batch-0fecfe9ea78e4807b9473b195c0038a1>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-0fecfe9ea78e4807b9473b195c0038a1\n",
      "distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7f5dca6c3730> of <Future: status: cancelled, key: _fit_and_score-batch-d5a39f7da6ca45139d40fad64cfd50e6>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 287, in execute_callback\n",
      "    fn(fut)\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\", line 260, in callback_wrapper\n",
      "    result = future.result()\n",
      "  File \"/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\", line 224, in result\n",
      "    raise result\n",
      "concurrent.futures._base.CancelledError: _fit_and_score-batch-d5a39f7da6ca45139d40fad64cfd50e6\n"
     ]
    },
    {
     "ename": "CancelledError",
     "evalue": "_fit_and_score-batch-d5a39f7da6ca45139d40fad64cfd50e6",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mCancelledError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-23-9e8efe1ab9d8>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mjoblib\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mParallel\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mparallel_backend\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;32mwith\u001b[0m \u001b[0mparallel_backend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'dask'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 4\u001b[0;31m     \u001b[0mCV_rfc\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mX_train\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0my_train\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m/home/cdsw/.local/lib/python3.6/site-packages/sklearn/model_selection/_search.py\u001b[0m in \u001b[0;36mfit\u001b[0;34m(self, X, y, groups, **fit_params)\u001b[0m\n\u001b[1;32m    686\u001b[0m                 \u001b[0;32mreturn\u001b[0m \u001b[0mresults\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    687\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 688\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_run_search\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mevaluate_candidates\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    689\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    690\u001b[0m         \u001b[0;31m# For multi-metric evaluation, store the best_index_, best_params_ and\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/cdsw/.local/lib/python3.6/site-packages/sklearn/model_selection/_search.py\u001b[0m in \u001b[0;36m_run_search\u001b[0;34m(self, evaluate_candidates)\u001b[0m\n\u001b[1;32m   1147\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_run_search\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mevaluate_candidates\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1148\u001b[0m         \u001b[0;34m\"\"\"Search all candidates in param_grid\"\"\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1149\u001b[0;31m         \u001b[0mevaluate_candidates\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mParameterGrid\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mparam_grid\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1150\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1151\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/cdsw/.local/lib/python3.6/site-packages/sklearn/model_selection/_search.py\u001b[0m in \u001b[0;36mevaluate_candidates\u001b[0;34m(candidate_params)\u001b[0m\n\u001b[1;32m    665\u001b[0m                                \u001b[0;32mfor\u001b[0m \u001b[0mparameters\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mtrain\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtest\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    666\u001b[0m                                in product(candidate_params,\n\u001b[0;32m--> 667\u001b[0;31m                                           cv.split(X, y, groups)))\n\u001b[0m\u001b[1;32m    668\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    669\u001b[0m                 \u001b[0;32mif\u001b[0m \u001b[0mlen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mout\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m<\u001b[0m \u001b[0;36m1\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/cdsw/.local/lib/python3.6/site-packages/joblib/parallel.py\u001b[0m in \u001b[0;36m__call__\u001b[0;34m(self, iterable)\u001b[0m\n\u001b[1;32m   1014\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1015\u001b[0m             \u001b[0;32mwith\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_backend\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mretrieval_context\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1016\u001b[0;31m                 \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mretrieve\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1017\u001b[0m             \u001b[0;31m# Make sure that we get a last message telling us we are done\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1018\u001b[0m             \u001b[0melapsed_time\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtime\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtime\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m-\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_start_time\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/cdsw/.local/lib/python3.6/site-packages/joblib/parallel.py\u001b[0m in \u001b[0;36mretrieve\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    908\u001b[0m                     \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_output\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mextend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mjob\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    909\u001b[0m                 \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 910\u001b[0;31m                     \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_output\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mextend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mjob\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    911\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    912\u001b[0m             \u001b[0;32mexcept\u001b[0m \u001b[0mBaseException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mexception\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/cdsw/.local/lib/python3.6/site-packages/joblib/_dask.py\u001b[0m in \u001b[0;36mget\u001b[0;34m()\u001b[0m\n\u001b[1;32m    268\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    269\u001b[0m         \u001b[0;32mdef\u001b[0m \u001b[0mget\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 270\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0mref\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mresult\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    271\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    272\u001b[0m         \u001b[0mfuture\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mget\u001b[0m  \u001b[0;31m# monkey patch to achieve AsyncResult API\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/cdsw/.local/lib/python3.6/site-packages/distributed/client.py\u001b[0m in \u001b[0;36mresult\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    222\u001b[0m             \u001b[0;32mraise\u001b[0m \u001b[0mexc\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwith_traceback\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtb\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    223\u001b[0m         \u001b[0;32melif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstatus\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;34m\"cancelled\"\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 224\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mresult\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    225\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    226\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0mresult\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mCancelledError\u001b[0m: _fit_and_score-batch-d5a39f7da6ca45139d40fad64cfd50e6"
     ]
    }
   ],
   "source": [
    "# ### Fit Model with Dask\n",
    "from joblib import Parallel, parallel_backend\n",
    "with parallel_backend('dask'):\n",
    "    CV_rfc.fit(X_train, y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ### Show Best Parameters \n",
    "print(CV_rfc.best_params_)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Evaluate model performance"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.metrics import classification_report\n",
    "# ## fit test dataset \n",
    "y_true, y_pred = y_test, CV_rfc.predict(X_test)\n",
    "# ## Print classification metrics \n",
    "print(classification_report(y_true, y_pred))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "## Optional - print dask cluster config \n",
    "\n",
    "import json\n",
    "print(json.dumps(client.scheduler_info(), indent=4))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Stop CDSW Workers"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "## stop CDSW workers\n",
    "import cdsw\n",
    "cdsw.stop_workers()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
